import { Industry, SCORProcess, Difficulty } from './types';

export const SCENARIOS = {
  // Electronics & Tech Scenarios
  SUPPLY_DISRUPTION: {
    id: 'ELEC-A',
    title: 'Supply Disruption at Key Supplier',
    scorStages: [SCORProcess.SOURCE],
    situation: 'A major supplier of microchips halts production unexpectedly, causing critical shortages and production delays for your new smartphone line.',
    impacts: ['High dependency on this supplier.', 'Alternative supplier available but with 30% higher cost.', 'Production downtime estimated at five days.'],
    responses: [
      { id: 'A', text: 'Wait for supplier recovery', impact: '0% cost, 10-day delay', cost: 0, time: 10, risk: 9 },
      { id: 'B', text: 'Shift to alternate supplier', impact: '+30% cost, 5-day delay', cost: 30, time: 5, risk: 4 },
      { id: 'C', text: 'Split sourcing', impact: '+15% cost, 3-day delay', cost: 15, time: 3, risk: 2 },
      { id: 'D', text: 'Redesign product to reduce dependency', impact: '+20% cost, long-term independence', cost: 20, time: 20, risk: 1 },
    ],
    feedback: 'Options B and C ensure continuity; D builds long-term resilience.',
    difficulty: Difficulty.EASY,
  },
  SUSTAINABILITY_PRESSURE: {
      id: 'ELEC-B',
      title: 'Sustainability Pressure on Global Electronics Manufacturer',
      scorStages: [SCORProcess.PLAN, SCORProcess.SOURCE],
      situation: 'An electronics firm faces increasing climate-related disruptions and supplier vulnerability to extreme weather. You must integrate sustainability into supply planning and supplier selection.',
      impacts: ['Risks involve production halts, regulatory pressure, and investor scrutiny.'],
      responses: [
          { id: 'A', text: 'Maintain current supply base', impact: 'Low cost, high climate risk', cost: 0, time: 0, risk: 9 },
          { id: 'B', text: 'Diversify suppliers geographically', impact: '+15% cost, medium risk reduction', cost: 15, time: 5, risk: 5 },
          { id: 'C', text: 'Invest in green energy sourcing with key suppliers', impact: '+25% cost, high risk reduction', cost: 25, time: 10, risk: 2 },
          { id: 'D', text: 'Lobby against new climate regulations', impact: '+5% cost, high reputation risk', cost: 5, time: 0, risk: 10 },
      ],
      feedback: 'Investing in green sourcing (C) and diversification (B) are strong strategies for long-term resilience.',
      difficulty: Difficulty.HARD,
  },
  // Logistics Scenarios
  CYBER_ATTACK: {
    id: 'LOG-A',
    title: 'Cyber-Attack on Logistics System',
    scorStages: [SCORProcess.DELIVER],
    situation: 'A ransomware attack disables the customs clearance and shipment tracking system for your global logistics network.',
    impacts: ['60% of shipments delayed.', 'Penalties for late delivery after 5 days.', 'Customer dissatisfaction rising daily.'],
    responses: [
      { id: 'A', text: 'Wait for internal IT recovery', impact: '0% cost, 10-day delay', cost: 0, time: 10, risk: 8 },
      { id: 'B', text: 'Divert shipments to unaffected ports', impact: '+15% cost, 3-day delay', cost: 15, time: 3, risk: 4 },
      { id: 'C', text: 'Air freight critical orders', impact: '+40% cost, maintain delivery schedule', cost: 40, time: 0, risk: 2 },
      { id: 'D', text: 'Collaborate with port authority on manual clearance', impact: '+10% cost, 5-day delay', cost: 10, time: 5, risk: 5 },
    ],
    feedback: 'B offers a balanced performance by rerouting; C maximizes service reliability for key clients at a high cost.',
    difficulty: Difficulty.MEDIUM,
  },
  FREIGHT_CAPACITY_SHORTAGE: {
    id: 'LOG-B',
    title: 'Freight Capacity Shortage',
    scorStages: [SCORProcess.DELIVER],
    situation: 'Container availability drops globally, tripling freight rates and creating massive backlogs at ports.',
    impacts: ['Critical orders face long delays.', 'Penalties for missed deadlines apply after 7 days.', 'Customers threatening to switch providers.'],
    responses: [
      { id: 'A', text: 'Wait for normalization', impact: '0% cost, long delay', cost: 0, time: 30, risk: 9 },
      { id: 'B', text: 'Secure high-cost capacity', impact: '+200% cost, on-time delivery', cost: 200, time: 0, risk: 2 },
      { id: 'C', text: 'Shift to regional transport (truck/rail)', impact: '+50% cost, moderate delay', cost: 50, time: 10, risk: 4 },
      { id: 'D', text: 'Collaborate with competitors for shared capacity', impact: '+80% cost, shared benefit', cost: 80, time: 15, risk: 3 },
    ],
    feedback: 'D balances cost and reliability through strategic collaboration; B ensures full service continuity for those who can afford it.',
    difficulty: Difficulty.HARD,
  },
  CORRUPTION_RISK: {
      id: 'LOG-C',
      title: 'Corruption Risk in Freight Clearance',
      scorStages: [SCORProcess.DELIVER, SCORProcess.ENABLE],
      situation: 'Local customs officials at a key international port are demanding unofficial payments for expedited clearance, creating ethical and legal risks.',
      impacts: ['Ethical and legal risk of bribery.', 'Potential for severe regulatory penalties and fines.'],
      responses: [
          { id: 'A', text: 'Continue paying to ensure speed', impact: 'Short-term speed, high risk', cost: 5, time: 0, risk: 10 },
          { id: 'B', text: 'Enforce strict compliance systems and report demands', impact: '+10% cost, potential delays, transparent operations', cost: 10, time: 7, risk: 3 },
          { id: 'C', text: 'Work with trade associations to address the issue', impact: '+15% cost, long-term reform', cost: 15, time: 20, risk: 2 },
          { id: 'D', text: 'Shift to alternate ports immediately', impact: '+20% cost, stable flow', cost: 20, time: 5, risk: 4 },
      ],
      feedback: 'Enforcing compliance (B) ensures integrity and is a responsible immediate step. C fosters sustainable, systemic change.',
      difficulty: Difficulty.HARD,
  },
  // Apparel & Fashion Scenarios
  LABOR_COMPLIANCE_SCANDAL: {
      id: 'APP-A',
      title: 'Labor Compliance Scandal',
      scorStages: [SCORProcess.MAKE, SCORProcess.ENABLE],
      situation: 'A global apparel producer faces credible allegations of labor rights violations and unsafe conditions at a major supplier factory.',
      impacts: ['Severe reputation damage risk.', 'Protests and boycotts are emerging across key markets.'],
      responses: [
          { id: 'A', text: 'Deny allegations and launch a PR campaign', impact: '0% cost, reputation collapse risk', cost: 0, time: 0, risk: 10 },
          { id: 'B', text: 'Conduct immediate independent audits', impact: '+10% cost, partial recovery', cost: 10, time: 5, risk: 6 },
          { id: 'C', text: 'Replace supplier and publicize new ethical standards', impact: '+25% cost, rebuild trust', cost: 25, time: 15, risk: 2 },
          { id: 'D', text: 'Relocate production to an in-house facility', impact: '+40% cost, improved compliance', cost: 40, time: 30, risk: 1 },
      ],
      feedback: 'Replacing the supplier (C) offers a path to sustainable recovery and trust-building; Audits (B) are a necessary first step but may not be enough.',
      difficulty: Difficulty.HARD,
  },
  OVERSTOCK_CRISIS: {
      id: 'APP-B',
      title: 'Overstock Crisis in Retail',
      scorStages: [SCORProcess.PLAN, SCORProcess.MAKE],
      situation: 'A fashion retailer badly misforecasts seasonal demand, leading to massive amounts of unsold stock and warehouse storage overflow.',
      impacts: ['Excess inventory causes severe cash-flow strain.', 'Warehouses are operating at full capacity, incurring extra costs.'],
      responses: [
          { id: 'A', text: 'Implement deep discounts to liquidate stock', impact: 'Rapid cash, low profit', cost: -50, time: 0, risk: 5 },
          { id: 'B', text: 'Store for next season and hope trends return', impact: 'Low cost, high obsolescence risk', cost: 5, time: 0, risk: 8 },
          { id: 'C', text: 'Recycle or repurpose textiles into a new product line', impact: '+15% cost, sustainability gain', cost: 15, time: 10, risk: 3 },
          { id: 'D', text: 'Implement AI-powered digital forecasting', impact: '+20% cost, long-term efficiency', cost: 20, time: 15, risk: 1 },
      ],
      feedback: 'Implementing digital forecasting (D) addresses the root cause and improves strategic planning. Recycling (C) supports CSR goals and mitigates losses.',
      difficulty: Difficulty.EASY,
  },
  // Food & Beverages Scenarios
  FOOD_TRACEABILITY: {
      id: 'FOOD-A',
      title: 'Food Traceability Through Blockchain',
      scorStages: [SCORProcess.SOURCE, SCORProcess.DELIVER],
      situation: 'Following a food safety scare, consumers are demanding absolute proof of product origin and quality to combat counterfeit goods and ensure safety.',
      impacts: ['Increasing customer complaints about authenticity.', 'Major retail partners are requesting certification of origin.'],
      responses: [
          { id: 'A', text: 'Maintain current QR code tracking', impact: 'Low cost, low trust', cost: 0, time: 0, risk: 8 },
          { id: 'B', text: 'Implement partial blockchain for key products', impact: '+20% cost, moderate transparency', cost: 20, time: 10, risk: 4 },
          { id: 'C', text: 'Adopt full blockchain traceability from farm to shelf', impact: '+40% cost, brand leadership', cost: 40, time: 20, risk: 1 },
          { id: 'D', text: 'Use third-party certification service', impact: '+25% cost, limited control', cost: 25, time: 5, risk: 6 },
      ],
      feedback: 'Partial blockchain (B) offers a good balance of cost and benefit. Full blockchain (C) builds strong brand trust and leadership.',
      difficulty: Difficulty.MEDIUM,
  },
  PANDEMIC_WORKFORCE_SHORTAGE: {
      id: 'FOOD-B',
      title: 'Pandemic-Induced Workforce Shortage',
      scorStages: [SCORProcess.PLAN, SCORProcess.MAKE],
      situation: 'A global health crisis reduces workforce availability in your food processing plants and disrupts the material flow of ingredients.',
      impacts: ['Production capacity is down 35%.', 'Demand for essential goods has doubled.', 'Rising absenteeism due to illness.'],
      responses: [
          { id: 'A', text: 'Maintain operations with overtime', impact: 'No cost, high burnout risk', cost: 0, time: 0, risk: 9 },
          { id: 'B', text: 'Partially automate the production line', impact: '+25% cost, +15% capacity', cost: 25, time: 20, risk: 2 },
          { id: 'C', text: 'Prioritize essential products only', impact: '+10% cost, improved service reliability', cost: 10, time: 2, risk: 4 },
          { id: 'D', text: 'Collaborate regionally for shared capacity', impact: '+20% cost, improved resilience', cost: 20, time: 5, risk: 3 },
      ],
      feedback: 'Automation (B) and regional collaboration (D) are the most resilient long-term strategies. Prioritizing products (C) is an effective short-term efficiency measure.',
      difficulty: Difficulty.HARD,
  },
  // Pharmaceuticals Scenarios
  COLD_CHAIN_FAILURE: {
    id: 'PHARMA-A',
    title: 'Cold Chain Logistics Failure',
    scorStages: [SCORProcess.DELIVER, SCORProcess.ENABLE],
    situation: 'A shipment of temperature-sensitive vaccines experiences a cooling system failure during transit, rendering the entire multi-million dollar batch unusable.',
    impacts: ['Total loss of product value.', 'Critical delivery deadlines for a national health program missed.', 'Severe public health and reputation implications.'],
    responses: [
      { id: 'A', text: 'Expedite a new shipment via premium air freight', impact: '+50% cost, 2-day delay', cost: 50, time: 2, risk: 2 },
      { id: 'B', text: 'Source from a closer, secondary facility at higher cost', impact: '+25% cost, 5-day delay', cost: 25, time: 5, risk: 4 },
      { id: 'C', text: 'Inform stakeholders of a long delay and reschedule', impact: '0% cost, 15-day delay', cost: 0, time: 15, risk: 9 },
      { id: 'D', text: 'Invest in real-time temp monitoring & backup cooling', impact: '+30% cost, long-term risk reduction', cost: 30, time: 30, risk: 1 },
    ],
    feedback: 'Investing in technology (D) is a proactive, long-term solution. Expediting (A) is a necessary reactive measure to meet immediate, critical needs.',
    difficulty: Difficulty.HARD,
  },
  REGULATORY_HURDLE: {
    id: 'PHARMA-B',
    title: 'Regulatory Compliance Hurdle',
    scorStages: [SCORProcess.PLAN, SCORProcess.MAKE],
    situation: "A new drug's final approval is delayed by regulators requesting additional manufacturing process data that was not anticipated.",
    impacts: ['Delayed market entry costs millions in potential revenue.', 'Potential loss of valuable patent life.', 'Stock price volatility.'],
    responses: [
      { id: 'A', text: "Challenge the regulator's request legally", impact: '+10% cost, 60-day delay', cost: 10, time: 60, risk: 8 },
      { id: 'B', text: 'Comply and gather data, pausing production', impact: '+5% cost, 30-day delay', cost: 5, time: 30, risk: 3 },
      { id: 'C', text: 'Switch production to an approved facility in another region', impact: '+40% cost, 10-day delay', cost: 40, time: 10, risk: 5 },
      { id: 'D', text: 'Implement a digital twin for manufacturing for real-time data', impact: '+35% cost, long-term compliance efficiency', cost: 35, time: 45, risk: 1 },
    ],
    feedback: 'Proactive digital solutions (D) streamline future compliance. Complying quickly (B) is the most direct path to approval despite the delay.',
    difficulty: Difficulty.MEDIUM,
  },
  // Automotive Scenarios
  JIT_DISRUPTION: {
    id: 'AUTO-A',
    title: 'Just-in-Time (JIT) Disruption',
    scorStages: [SCORProcess.SOURCE, SCORProcess.MAKE],
    situation: 'A key supplier of transmissions has a factory strike, halting your entire vehicle assembly line which operates on a Just-in-Time (JIT) inventory model.',
    impacts: ['Daily production loss is in the millions.', 'Dealer inventories are depleting rapidly.', 'Risk of losing market share to competitors.'],
    responses: [
      { id: 'A', text: 'Wait for the strike to resolve', impact: '0% cost, 20-day delay', cost: 0, time: 20, risk: 9 },
      { id: 'B', text: 'Airlift a limited supply from an overseas supplier', impact: '+80% cost, 3-day delay', cost: 80, time: 3, risk: 3 },
      { id: 'C', text: 'Re-tool a section of the line for a different model', impact: '+30% cost, 15-day delay', cost: 30, time: 15, risk: 6 },
      { id: 'D', text: 'Shift from pure JIT to holding safety stock of critical parts', impact: '+15% cost, long-term resilience', cost: 15, time: 5, risk: 1 },
    ],
    feedback: "Holding safety stock (D) counters JIT's main vulnerability. Airlifting parts (B) is a costly but effective stop-gap to maintain production.",
    difficulty: Difficulty.MEDIUM,
  },
  EV_BATTERY_SOURCING: {
    id: 'AUTO-B',
    title: 'EV Battery Sourcing Ethics',
    scorStages: [SCORProcess.SOURCE, SCORProcess.ENABLE],
    situation: 'A media report exposes unethical labor practices at the mine supplying cobalt for your EV batteries, sparking public outrage and calls for a boycott.',
    impacts: ['Major brand reputation damage.', 'Potential for consumer boycotts affecting sales.', 'Investor pressure to change suppliers.'],
    responses: [
      { id: 'A', text: 'Ignore the report and issue a denial', impact: '0% cost, catastrophic reputation risk', cost: 0, time: 0, risk: 10 },
      { id: 'B', text: 'Terminate supplier and find a certified ethical source', impact: '+25% cost, 10-day delay', cost: 25, time: 10, risk: 2 },
      { id: 'C', text: 'Work with the supplier to improve conditions & fund audits', impact: '+10% cost, long-term process', cost: 10, time: 30, risk: 5 },
      { id: 'D', text: 'Invest heavily in R&D for cobalt-free batteries', impact: '+50% cost, long-term strategic advantage', cost: 50, time: 60, risk: 1 },
    ],
    feedback: 'Terminating the contract (B) is a strong, immediate ethical stance. Investing in R&D (D) is a visionary move that solves the problem at its root.',
    difficulty: Difficulty.HARD,
  }
};

export const INDUSTRIES: Industry[] = [
  {
    id: 'electronics',
    name: 'Electronics & Technology',
    description: 'Manage high-value components and rapid innovation cycles.',
    scenarios: [SCENARIOS.SUPPLY_DISRUPTION, SCENARIOS.SUSTAINABILITY_PRESSURE],
  },
  {
    id: 'apparel',
    name: 'Apparel & Fashion',
    description: 'Navigate seasonal demand, ethical sourcing, and overstock risks.',
    scenarios: [SCENARIOS.LABOR_COMPLIANCE_SCANDAL, SCENARIOS.OVERSTOCK_CRISIS],
  },
  {
    id: 'logistics',
    name: 'Logistics & Supply Chain',
    description: 'Tackle global disruptions from cyber-attacks to capacity shortages.',
    scenarios: [SCENARIOS.CYBER_ATTACK, SCENARIOS.FREIGHT_CAPACITY_SHORTAGE, SCENARIOS.CORRUPTION_RISK],
  },
  {
    id: 'food',
    name: 'Food & Beverages',
    description: 'Ensure safety, traceability, and resilience in the food supply chain.',
    scenarios: [SCENARIOS.FOOD_TRACEABILITY, SCENARIOS.PANDEMIC_WORKFORCE_SHORTAGE],
  },
  {
    id: 'pharma',
    name: 'Pharmaceuticals',
    description: 'Handle strict regulations, cold chain logistics, and patent cliffs.',
    scenarios: [SCENARIOS.COLD_CHAIN_FAILURE, SCENARIOS.REGULATORY_HURDLE],
  },
  {
    id: 'auto',
    name: 'Automotive',
    description: 'Balance Just-in-Time manufacturing with EV transitions and ethical sourcing.',
    scenarios: [SCENARIOS.JIT_DISRUPTION, SCENARIOS.EV_BATTERY_SOURCING],
  },
];
